#!/bin/bash -e



if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
  dpkg-maintscript-helper rm_conffile /etc/kde3/kdeglobals 6.0.1 -- "$@"
fi

if [ "${1}" = "configure" ] && [ "$2" != "" ] ; then

    if dpkg --compare-versions ${2} lt 0.3.11 && dpkg --compare-versions ${2} gt 0.3.5; then
        if test -x /var/lib/dpkg/info/libgnome2-common.postinst; then
            /var/lib/dpkg/info/libgnome2-common.postinst configure
        fi
    fi
fi

if [ "$1" = "configure" -o "$1" = "abort-upgrade" ]; then
    # Alternatives for the background
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background \
        desktop-background \
        /usr/share/images/desktop-base/spacefun-wallpaper.svg 60

    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background \
        desktop-background \
        /usr/share/images/desktop-base/spacefun-wallpaper-widescreen.svg  55

    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background \
        desktop-background \
        /usr/share/images/desktop-base/moreblue-orbit-wallpaper.svg 50

    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background \
        desktop-background \
        /usr/share/images/desktop-base/moreblue-orbit-wallpaper-widescreen.svg  50

    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background \
        desktop-background \
        /usr/share/images/desktop-base/nightly-wallpaper.png 40

    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background \
        desktop-background \
        /usr/share/images/desktop-base/debian-blueish-wallpaper.svg 30

    # Alternatives for the splash
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-splash \
        desktop-splash \
        /usr/share/images/desktop-base/spacefun-splash.svg 50

    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-splash \
        desktop-splash \
        /usr/share/images/desktop-base/moreblue-orbit-splash.png 40

    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-splash \
        desktop-splash \
        /usr/share/images/desktop-base/gnome-splash-curves.png 30

    # Alternatives for grub
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-grub.png \
        desktop-grub \
        /usr/share/images/desktop-base/spacefun-grub.png 15

    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-grub.png \
        desktop-grub \
        /usr/share/images/desktop-base/spacefun-grub-widescreen.png 14

    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-grub.png \
        desktop-grub \
        /usr/share/images/desktop-base/moreblue-orbit-grub.png 10

    # GRUB background
    if which update-grub2 > /dev/null ; then
        sync
        update-grub2 || true
    fi

    # Splashy
    if [ -x /sbin/splashy_config ] && [ -w /etc/splashy/config.xml ]; then
        splashy_config --set-theme spacefun
    fi

    # Plymouth
    #if [ -x /usr/sbin/plymouth-set-default-theme ];
    #then
    #  plymouth-set-default-theme spacefun ||true
    #fi

    if [ -x /usr/sbin/update-initramfs ]; then
        update-initramfs -u
    fi
fi
