#!/bin/sh

set -e

if [ "$1" = "configure" ] && dpkg --compare-versions "$2" eq "1.0.0-2";
then
  cd /usr/share/doc/thunar && rm -f thunar-data
fi

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section


exit 0
