.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH TINT2 1 "2009-01-17"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
tint2 \- lightweight panel/taskbar
.SH SYNOPSIS
.B tint2
.br
.B tint2
.RI -c
.IR /path_to_config_file 
.SH DESCRIPTION
This manual page documents briefly the
.B tint2
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBtint2\fP is a simple panel/taskbar intentionally made for openbox3, but 
should also work with other window managers. It's based on ttm code. The goal is to keep a clean and unintrusive look with code lightweight and 
compliance with freedesktop specifications.
.PP
On the first startup tint2 creates a config file in $HOME/.config/tint2/tint2rc.
.PP
See wiki page on http://code.google.com/p/tint2/wiki/Welcome for more information.
.SH OPTIONS
.TP
.B \-c config-file
Specify which configuration file to use instead of the default.
.SH AUTHOR
tint2 was written by Thierry Lorthiois <lorthiois@bbsoft.fr>.  It is based on
ttm, originally written by Pål Staurland <staura@gmail.com>
.PP
This manual page was written by Daniel Moerner <dmoerner@gmail.com>,
for the Debian project (but may be used by others).  It was adopted from the
tint2 docs.
