#!/bin/bash -ex

if [[ -f /etc/apt/sources.list ]] && [[ ! -f /etc/apt/sources.list.d/debian.sources ]]; then
cat << EOF > /etc/apt/sources.list.d/debian.sources
# Add 'deb-src' to Types line for source packages
Types: deb
URIs: http://deb.debian.org/debian/
Suites: trixie trixie-updates trixie-backports
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb
URIs: http://security.debian.org/debian-security/
Suites: trixie-security
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOF
rm /etc/apt/sources.list
rm /etc/apt/sources.list~
fi

systemctl disable cbpp-apt-setup
rm /usr/lib/systemd/system/cbpp-apt-setup.service
rm -rf /usr/lib/cbpp
