#!/bin/sh
#
# $Id$
#
# Copyright (c) 2004-2006 Benedikt Meurer <benny@xfce.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

HELPDIR="/usr/share/doc/thunar-data/html/"

if test -n "$LC_ALL"; then
  LC=$LC_ALL
elif test -n "$LANG"; then
  LC=$LANG
else
  LC="C"
fi

if test -n "$1"; then
  HELPFILE="$1.html"
else
  HELPFILE="index.html"
fi

if test -r "$HELPDIR/$LC/$HELPFILE"; then
  URL="$HELPDIR/$LC/$HELPFILE"
elif test -r "$HELPDIR/`echo $LC | sed 's/\(..\)_.*/\1/'`/$HELPFILE"; then
  URL="$HELPDIR/`echo $LC | sed 's/\(..\)_.*/\1/'`/$HELPFILE"
else 
  URL="$HELPDIR/C/index.html"
fi

[ -n "$2" ] && URL="$URL#$2"

exec exo-open --launch WebBrowser "file://$URL"

# vim:set ts=2 sw=2 et ai:
