#!/bin/bash
#CrunchBang User Set-up

USER="$1"

if [ ! -f "/home/$USER/.config/crunchbang/cb-setup" ]; then

    cd /etc/skel
    tar cpzf skel.tar.gz .
    mv skel.tar.gz /home/$USER/skel.tar.gz
    cd /home/$USER
    tar xkpsf skel.tar.gz
    rm skel.tar.gz

    if [ -f "/home/$USER/.gtk-bookmarks" ]; then
        rpl -q 'REPLACEME' $USER /home/$USER/.gtk-bookmarks > /dev/null 2>&1
    fi
    ln -s /usr/share/backgrounds /home/$USER/images/wallpapers/shared

    touch /home/$USER/.config/crunchbang/cb-setup
    chown -R $USER:$USER /home/$USER

    #Fix for VLC within a live session whereby the binary does
    #does not know where the plugin directory is located.
    if [ -d /live/overlay ]; then
        if [ ! -x "/usr/bin/vlc.real" ]; then
            if [ -x "/usr/bin/vlc" ]; then
                mv /usr/bin/vlc /usr/bin/vlc.real
                cat > /usr/bin/vlc << EOF
#!/bin/bash
#There is an issue with VLC not starting in a live session.
#This is a wrapper script to fix the issue
export VLC_PLUGIN_PATH=/usr/lib/vlc/
/usr/bin/vlc.real "\$@"
exit 0
EOF
                chmod +x /usr/bin/vlc
            fi
        fi
    fi
fi
exit 0
